#!/usr/bin/env Rscript

library(scriptr)
library(magrittr)

stuff <- command("Print a warm greeting.") %>%
  option("--name", "-n", type = "character", help = "Name to be greeted.") %>%
  option("--count", "-c", default = 1, help = "Number of times to greet.") %>%
  option("--lang", "-l", default = "en", choice = c("en", "es", "se", "jp"),
         help = "Language to greet in.") %>%
  option("--yell", "-y", is.flag = TRUE, help = "Greet with enthusiasm!") %>%
  parse_args()

# note this data structure is temporary
cat(sprintf('Options: %s\n', paste0(names(stuff), '=', stuff, collapse=', ')))
cat(sprintf('Arguments: %s\n', paste(attr(stuff, 'positional'), collapse=', ')))
